### ISSUE TITLE
Milestone 1 Submission

### ISSUE THREAD

**Issue by showcy** [UBC-MDS/cherry_blossom_tracker#4]
- [x] Create a release on GitHub.com before the submission deadline. Name your release with the respective milestone name.
- [x] Submit the link of the release.
- [x] You should paste in Gradescope the link to the team work contract and the link to the GitHub repo
- [x] Remember to add in Gradescope all the members of the group

**Comment by showcy** [comment]
<img width="1613" alt="Screen Shot 2022-02-18 at 7 29 18 PM" src="https://user-images.githubusercontent.com/27760215/154784420-d75c8e12-82c3-47f1-9ec2-31b8df7967c1.png">
Submitted. Please check.
